language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4

sudo: false
dist: trusty

services:

before_script:
    - php -d memory_limit=-1 `which composer` install

script:
    - composer test
